import { NavItem } from '@/model/common/nav'

// 9 位 id: 123456789 —— 123 代表产品 ID、456 代表树 ID、789 代表功能 ID
export const NavList: NavItem[] = [
  // 通用页面
  {
    id: '000000',
    isParent: true,
    path: '/',
    name: '通用页面',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000',
  },
  {
    id: '000000001',
    isParent: false,
    path: '/',
    name: '仪表盘',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000000',
  },
  // 核心运营管理
  {
    id: '000001',
    isParent: true,
    path: '/core',
    name: '核心运营管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000',
  },
  {
    id: '000001001',
    isParent: false,
    path: '/core/org',
    name: '组织架构管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000001',
  },
  {
    id: '000001002',
    isParent: false,
    path: '/core/admin',
    name: '运营人员管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000001',
  },
  {
    id: '000001003',
    isParent: false,
    path: '/core/role',
    name: '平台角色管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000001',
  },
  {
    id: '000001004',
    isParent: false,
    path: '/core/menu',
    name: '平台导航管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000001',
  },
  {
    id: '000001005',
    isParent: false,
    path: '/core/card',
    name: '平台卡片管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000001',
  },
  // 社区服务管理
  {
    id: '000002',
    isParent: true,
    path: '/service',
    name: '社区服务管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000',
  },
  {
    id: '000002001',
    isParent: false,
    path: '/service/activity/third',
    name: '三方活动管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000002',
  },
  {
    id: '000002002',
    isParent: false,
    path: '/service/recruit/third',
    name: '三方招聘管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000002',
  },
  {
    id: '000002003',
    isParent: false,
    path: '/service/chat/third',
    name: '三方群聊管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000002',
  },
  {
    id: '000002004',
    isParent: false,
    path: '/service/form/third',
    name: '三方表单管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000002',
  },
  // 社区建设管理
  {
    id: '000003',
    isParent: true,
    path: '/external',
    name: '社区建设管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000',
  },
  {
    id: '000003001',
    isParent: false,
    path: '/external/member',
    name: '社区成员管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000003',
  },
  {
    id: '000003002',
    isParent: false,
    path: '/external/notice',
    name: '社区公告管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000003',
  },
  // 平台资源管理
  {
    id: '000004',
    isParent: true,
    path: '/resource',
    name: '平台资源管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000',
  },
  {
    id: '000004001',
    isParent: false,
    path: '/resource/platform',
    name: '三方平台管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000004',
  },
  {
    id: '000004002',
    isParent: false,
    path: '/resource/entity',
    name: '实体物资管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000004',
  },
  {
    id: '000004003',
    isParent: false,
    path: '/resource/account',
    name: '虚拟账号管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000004',
  },
  {
    id: '000004004',
    isParent: false,
    path: '/resource/file',
    name: '线上文件管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000004',
  },
  {
    id: '000004005',
    isParent: false,
    path: '/resource/asset',
    name: '金融资产管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000004',
  },
  // 平台建设管理
  {
    id: '000005',
    isParent: true,
    path: '/internal',
    name: '平台建设管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000',
  },
  {
    id: '000005001',
    isParent: false,
    path: '/internal/lector',
    name: '社区讲师管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000005',
  },
  {
    id: '000005002',
    isParent: false,
    path: '/internal/yard',
    name: '社区场地管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000005',
  },
  {
    id: '000005003',
    isParent: false,
    path: '/internal/sponsor',
    name: '社区赞助管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000005',
  },
  // 平台文档管理
  {
    id: '000006',
    isParent: true,
    path: '/doc',
    name: '平台文档管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000',
  },
  {
    id: '000006001',
    isParent: false,
    path: '/doc/dictionary',
    name: '数据字典管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000006',
  },
  {
    id: '000006002',
    isParent: false,
    path: '/doc/operate',
    name: '操作日志管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000006',
  },
  // 运营人员中心
  {
    id: '000007',
    isParent: true,
    path: '/admin',
    name: '运营人员中心',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000',
  },
  {
    id: '000007001',
    isParent: false,
    path: '/admin/profile',
    name: '个人资料管理',
    icon: 'dashboard',
    status: 'CODING',
    description: '',
    pid: '000007',
  },
  {
    id: '000007002',
    isParent: false,
    path: '/admin/custom',
    name: '平台定制管理',
    icon: 'dashboard',
    status: 'DISABLED',
    description: '',
    pid: '000007',
  },
]
